import type { Metadata } from "next";
import "./globals.css";
import "the-new-css-reset/css/reset.css";
import { AppProvider } from "@/context/AppContext";
import Header from "@/components/Header";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ja">
      <AppProvider>
        <body>
          <Header/>
          {children}
        </body> 
      </AppProvider>
    </html>
  );
}
